---
# tasks file for roles/motd-banner
- name: Install Figlet
  become: yes
  become_method: su
  ansible.builtin.package:
    name: "figlet"
    state: latest
  tags:
    - install_packages
  
- name: Install Lolcat
  become: yes
  become_method: su
  apt:
    name: "lolcat"
    state: latest
  tags:
    - install_packages

- name: Create the banner file
  copy:
    dest: /etc/update-motd.d/10-my-banner
    content: |
      #!/bin/sh
      screenfetch
    force: true
    mode: 0755
    unsafe_writes: true
